---
development:
  adapter: sqlite3
  database: db/dev.db
  show_exceptions: true
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.db
  show_exceptions: true
  pool: 5
  timeout: 5000
